### PR TITLE
Add support for eSpeak-NG

### PR DESCRIPTION
**Pull request by olysonek**
It is mostly a copy of the eSpeak driver, hence I put the following to `Drivers/Speech/eSpeak-NG/Makefile.in`:
`DRIVER_DEVELOPERS = Nicolas Pitre <nico@fluxnic.net>, Ondřej Lysoněk <olysonek@redhat.com>`

### CODE REVIEW

**Comment by DaveMielke** [comment]
I made two types of changes after merging the eSpeak-NG speech driver:
1) Reordered lists that should be alphabetically sorted by driver code.
2) Undid changes to the derived Portuguese documents.

Do you have any idea what the NG means? Also, what do you think about using 
"ng", rather than "en", for the driver code?

What's your full name and email address (for the CONTRIBUTORS file)?

You left Nicolas as the author in the make file? Shall I change it to you?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by shindere** [comment]
Usually NG stands for New Generation, when a tool is rewritten
(potentially in another language) or receives very important changes.

**Comment by olysonek** [comment]
Thanks for the quick response!

> I made two types of changes after merging the eSpeak-NG speech driver:
> 1) Reordered lists that should be alphabetically sorted by driver code.

Ok. Sorry, I didn't notice it was alphabetically sorted.

> 2) Undid changes to the derived Portuguese documents.

Ok. My intention was not to leave any gaps in the Documentation. Are the Portugese files generated when you make a release?

> Do you have any idea what the NG means? Also, what do you think about using "ng", rather than "en", for the driver code?

NG stands for Next Generation. eSpeak-NG is the successor of the eSpeak project. The original eSpeak is not developed anymore. I have no problem with using "ng" as driver code. It might get a little confusing, if more NG projects get created in the future, but it doesn't matter to me. Shall I change the driver code to "ng" then?


> What's your full name and email address (for the CONTRIBUTORS file)?

My name is Ondřej Lysoněk, and email address is olysonek@redhat.com.

> You left Nicolas as the author in the make file? Shall I change it to you?

I put Nicolas and myself as the author, as the code is mostly a copy of the eSpeak driver. I didn't want to take credit for it. Feel free to change it, if you think it's appropriate.

Thanks!

**Comment by DaveMielke** [comment]
[quoted lines by olysonek on 2018/03/01 at 11:01 +0000]

>Ok. My intention was not to leave any gaps in the Documentation. 

I know. :-)

>Are the Portugese files generated when you make a release?

No. Unfortunately, they're just out-of-date. I'd rather have them consistently 
out-of-date, though.

>NG stands for Next Generation. eSpeak-NG is the successor of the eSpeak 
>project. The original eSpeak is not developed anymore. I have no problem with 
>using "ng" as driver code. It might get a little confusing, if more NG 
>projects get created in the future, but it doesn't matter to me. Shall I 
>change the driver code to "ng" then?

No. Now that I know what NG means, it's way to generic to be a driver code. I 
guess we'll stay with en. I don't particularly like it, but can't think of a 
better one.

>My name is Ondřej Lysoněk, and email address is olysonek@redhat.com.

Fixed. Thanks.

Do you know when Fedora will update LibLouis to at least 3.4.1? There are 
cursor routing issues in releases earlier than that. 3.5.0 should be out within 
a week or so, now.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by olysonek** [comment]
> Do you know when Fedora will update LibLouis to at least 3.4.1? There are cursor routing issues in releases earlier than that. 3.5.0 should be out within a week or so, now.

I don't know, and it seems there aren't currently plans to do that. But when 3.5.0 comes out, I will file a bug against liblouis in bugzilla. Just to save the maintainer the effort of updating to 3.4 and then to 3.5. You could also create the bug yourself, if it's no trouble. See the following link:
https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

**Comment by DaveMielke** [comment]
[quoted lines by olysonek on 2018/03/01 at 08:08 -0800]

Hi:

>I don't know, and it seems there aren't currently plans to do that. 

My Fedora 27 system has liblouis-2.6.2, and that's old. Orca relies on it, so 
it does matter. Also, brltty now has support for using liblouis and it'd be 
nice to eventually let it take care of contracted braille support.

>when 3.5.0 comes out, I will file a bug against liblouis in bugzilla. Just 
to save the maintainer the effort of updating to 3.4 and then to 3.5. 

Yes. 3.4.0 had a couple of problems, hence the 3.4.1 bug-fix release, but 
waiting a few days for 3.5.0 would indeed be the better choice.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Pull request merged**
