### PR TITLE
Build fixes for Solaris

### PR DESCRIPTION
**Pull request by alanc**
These are patches we've been using to build the brltty-5.4 packages for Solaris.

### CODE REVIEW

**Comment by DaveMielke** [comment]
Thanks. In configure.ac, I changed solaris2.1? to solaris2.1?* - I hope that's 
okay.

**Comment by alanc** [comment]
That's fine - I'd used ? just to skip over Solaris 2.1, but since that far predates the required XPG5 support it's not going to matter anyway.  I pulled your changes and it still builds okay for me here.

**Comment by DaveMielke** [comment]
Does Solaris have the ability to directly inspect the screen content so that we 
can look into writing a native screen driver for it? I recall that there was 
talk of doing that several years ago. Also, virtual consoles.

**Comment by alanc** [comment]
By "screen content" I assume you mean in tty mode?  (Since graphics mode is just the X Window System like most other Unixes.)  I don't know and would have to investigate it.

Virtual consoles are supported in Solaris 11 and later - the ioctls for them are documented on http://docs.oracle.com/cd/E53394_01/html/E54777/vt-7i.html

**Pull request merged**
