### PR TITLE
Adding Braille table for Ukrainian

### PR DESCRIPTION
**Pull request by vick08**
Added Braille table for Ukrainian (based on koi8-U)
Also, modified the lisst of tables in the docs

### CODE REVIEW

**Comment by DaveMielke** [comment]
I'm reluctant to accept this update because it removes what looks like a useful 
letter - \u0401, uppercase IO - from the Cyrillic subtable. Also, rather than 
updating the .csv file (which is derived), the right thing to do is to update 
brltty.cinf.in.

**Comment by vick08** [comment]
Thanks for being reluctant in accepting this commit. :)
Apparently, I messed up the ltr-cyrillic file when inserting new codes.
Hopefully, things will look better in the next commit.

**Comment by vick08** [comment]
Hope this one looks better!

**Comment by DaveMielke** [comment]
It's all merged, but I have a question regarding \u0457 (lowercase) and \u0407 
(uppercase). You call them Bilarussian Ukranian I with Diaeresis, but my 
Unicode table calls them the letter DOE. Are the names wrong or are the code 
points wrong?

**Comment by vick08** [comment]
Hi David.
Thanks for your questions.
I cross-checked the codes with wikipedia and the tables inside Mac OS's
character map.
The names are the same as used by VoiceOver on Mac.
They look correct to me since, when I switch to the Ukrainian or Russian
speech synthesizer, they are read as expected.
FYI, I am a native speaker of both languages. :)

**Comment by DaveMielke** [comment]
Hi:

I made a mistake. My Unicode table calls \u0407 and \u0457 the letter YI (with 
no accent). Is the letter YI the same as an I with a diaeresis?

It also says that they're just Cyrillic, i.e. no reference to either 
Byelorussian (that's the way Unicode spells it) or Ukranian.

Might it be that a Byelorussian or Ukranian I is a standard Cyrillic I with a 
diaeresis?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
Hi:

I looked them up two more ways. I searched Google with "unicode 0407", and I 
asked Java (on Android) what the character name for 0X0407 is. Both said it's 
the Cyrillic letter YI.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |
^

**Comment by vick08** [comment]
Hi David.
Yi is a correct description of this letter. Since it is only present in
Byelarussian and Ukrainian languages, hence was my description.
I can't say for Byelarussian, but in Ukrainian language, the letters I, EE,
YI and I-soft are different letters.

Hope this helps.
Victor

**Comment by DaveMielke** [comment]
Hi:

Thanks. I feel safe in changing the commented name, now. I like to make the 
names be the very same as Unicode calls them, but I'm cautious when it's a 
language that I don't know, and especially so when it's a person who knows that 
language.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
[quoted lines by Victor Tsaran on 2017/11/15 at 05:12 +0000]

>BTW, I think I need to submit an amend because, according to Wikipedia, the
>correct spelling the language of Belarus is Belarusian.

The problem from my end is that, rightly or wrongly, Unicode spells it the way 
it does and it's important for me that the tables and Unicode have the same 
names.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by vick08** [comment]
OK, so no change is necessary then?

**Pull request merged**
