### PR TITLE
Added Lithuanian Braille tables ported from liblouis.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
This adds/updates Lithuanian Braille tables.

Please note that I haven't tested them as I'm not a Braille user myself, and I haven't stumbled upon any documentation on how to actually run the tests. Any help in that regard would be appreciated.

I've ported these tables from liblouis, but being relatively fresh, they are likely to change in future, especially the 8-dot one.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@DaveMielke is there a way to verify input and output that these tables produce without a Braille display?

**Comment by DaveMielke** [comment]
BRLTTY comes with a tool called brltty-ctb (-h option for details) for testing 
contraction tables. Since BRLTTY only does output, only forward translation 
needs to be verified.

**Comment by rimas-kudelis** [comment]
Hi Dave!
I totally fail to understand this output:
```
$ ../Programs/brltty-ctb -t Text/lt.ttb -c Contraction/lt.ctb 
Įlinkdama fechtuotojo špaga sublykčiojusi pragręžė apvalų arbūzą.
iojusi�pragr~�apvals�arbkz�sublyk
```
The middle line here is input and the last one is output. This doesn't look valid at all to me, but more than that, I can't even understand what is going on and how on earth to fix this.

Also, is there a way to separately test and validate just the ttb table first? I see there's a `brltty-ttb` binary, but neither `-h`, nor `-H` explain what it does, and there's no manpage either.

BTW, the existance of `-H` argument itself seems quite unnecessary when its output differs from that of `-h` by just one extra line documenting the `-T` argument.

**Comment by DaveMielke** [comment]
[quoted lines by Rimas Kudelis on 2017/12/07 at 01:12 -0800]

>I totally fail to understand this output:
>```
>$ ../Programs/brltty-ctb -t Text/lt.ttb -c Contraction/lt.ctb 
>Įlinkdama fechtuotojo špaga sublykčiojusi pragręžė apvalų arbūzą.
>iojusi�pragr~�apvals�arbkz�sublyk
>```

>The middle line here is input and the last one is output. This doesn't look 
>valid at all to me, but more than that, I can't even understand what is going 
>on and how on earth to fix this.

Since it's a language and a braille code that I don't understand, I'll need 
some help before I can be helpful. One thing that I'd for sure find helpful is 
knowing wht actually is expected. It'd also help me if the bits of data could 
have identifying prefixes, e.g. "input:" "actual output:", and "expected 
output".

>Also, is there a way to separately test and validate just the ttb table first? 
>I see there's a `brltty-ttb` binary, but neither `-h`, nor `-H` explain what 
>it does, and there's no manpage either.

Just run brltty-ttb with the table as its only operand.

>BTW, the existance of `-H` argument itself seems quite unnecessary when its 
>output differs from that of `-h` by just one extra line documenting the `-T` 
>argument.

Maybe it seems unnecessary, but, please, don't be that way. Tehre's a reason - 
you just don't know it.

We have an API for processing options, and brltty itse4lf has lots of them. 
That's why -h and -H exist - -H doesn't show the options that most brlrty users 
aren't interested in and would consider to be little more than unwelcome noise. 
brltty-ttb, of course, uses that same option processing API, and it just so 
happens that it only has one of those options. Do you really expect me to mess 
up the whole mechanism just because you think that, in a case or two, it seems 
unnecessary?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
Maybe I'm coming across as a bit rude, and you don't actually understand 
what's bothering me. Perhaps I can illustrate with an example. In my opinion:

The wrong way: The way this is done looks stupid to me.
The right way: Why is this done that way?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
I'm sorry I disappeared. I was on the phone and had to fix an urgent bug.

I checked the contraction table code. To explicitly specify what an undefined 
character should be represented as you need to use an always rule to define the 
Unicode replacement character (\uFFFD).

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by rimas-kudelis** [comment]
No worries, it was time for me to wrap up and go to bed anyways.

I've specified \uFFFD in the update, but it didn't seem to have worked. But again, it's not a deal-breaker.

I've looked at brltty-ttb too, but it seems to work in a completely different way than brltty-ctb, so I wasn't able to test the Text table properly (or at least in a convenient way). Using it with brltty-ctb as the -t parameter results in rather unexpected output: all letters with diacritics are rendered incorrectly, and spaces are replaced with something else. I guess I'll try catching you on IRC again.

**Comment by DaveMielke** [comment]
[quoted lines by Rimas Kudelis on 2017/12/08 at 05:48 +0000]

>I've specified \uFFFD in the update, but it didn't seem to have worked.

It's commented out.

>I've looked at brltty-ttb too, but it seems to work in a completely different 
>way than brltty-ctb, so I wasn't able to test the Text table properly (or at 
>least in a convenient way). 

It looks like we haven't implemented that capability (yet). I can do so if 
you'd like.

>Using it with brltty-ctb as the -t parameter results in rather unexpected 
>output: all letters with diacritics are rendered incorrectly, and spaces are 
>replaced with something else. 

llease give me an example character or two (Unicoe and braille) and I'll have a 
look.

>I guess I'll try catching you on IRC again.

I'm not on IRC very often - just when I want to chat with the LibLouis dudes. 
Normally I passively monitor a few IM services in case family or (actual) 
friends want to get ahold of me.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by rimas-kudelis** [comment]
> >I've specified \uFFFD in the update, but it didn't seem to have worked.
>
> It's commented out.

Yeah, probably cause it didn't work.

But I'll probably uncomment it and make another PR. Or maybe not, cause 
I'm quite undecided – the question mark dots are fine by me, at least 
for now.

> >I've looked at brltty-ttb too, but it seems to work in a completely 
> different
> >way than brltty-ctb, so I wasn't able to test the Text table properly 
> (or at
> >least in a convenient way).
>
> It looks like we haven't implemented that capability (yet). I can do 
> so if
> you'd like.

Yes please!

I would also suggest to implement some sort of automated testing of 
tables, similar to liblouis. It seems you already have most of the 
necessary tools in place, all that is needed now is to script them.

> >Using it with brltty-ctb as the -t parameter results in rather 
> unexpected
> >output: all letters with diacritics are rendered incorrectly, and 
> spaces are
> >replaced with something else.
>
> llease give me an example character or two (Unicoe and braille) and 
> I'll have a
> look.

Here's a Lithuanian pangram text:

Įlinkdama fechtuotojo špaga sublykčiojusi pragręžė apvalų arbūzą.

When running it through `brltty-ctb` with -t parameter, I would expect 
the first letter to be lowercased and prefixed by something (dollar 
sign, I guess), but all other text to remain intact, because the 
mappings of lowercase letters, spaces and the full stop character are 
identical between 6-dot (Contraction) and 8-dot (Text) tables. But 
instead, all letters with diacritics are replaced with basic latin 
letters, control characters or other characters. Here's the output as 
displayed by `less`:

$/linkdama fechtuotojo apaga sublyk^Miojusi pragr^Y~^W apvals arbkz^E.

> >I guess I'll try catching you on IRC again.
>
> I'm not on IRC very often - just when I want to chat with the LibLouis 
> dudes.
> Normally I passively monitor a few IM services in case family or (actual)
> friends want to get ahold of me.

OK, thanks for the tip.

Cheers!

**Comment by DaveMielke** [comment]
Two things, since I can't look at a screen:

Am I correct that the first two characters in the text are a capital I with an 
ogonek accent followed by a lowercase l?

I need to know what the correct braille is. If you don't specify the text table 
(don't use -t), are the braille patterns correct?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
I've just fixed brltty-ctb. It was only writing the low-order byte of each 
character instead of the full characters in UTF-8.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke           | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: 1-613-726-0014 | Canada  K2A 1H7   |

**Comment by rimas-kudelis** [comment]
Cool! I ran my tests again and they look much more like what I expect this time. Thank you!

**Pull request merged**
