### PR TITLE
Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
This fixes building on Haiku, not really tested yet as I don't have hardware available.

### CODE REVIEW

**Comment by DaveMielke** [comment]
[quoted lines by François Revol on 2019/11/29 at 19:21 -0800]

>This fixes building on Haiku, not really tested yet as I don&#39;t have hardware available.

Haiku is new to me. What is it?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by mmuman** [comment]
> Haiku is new to me. What is it?

It's [a Free Software OS](https://www.haiku-os.org/), inspired by the BeOS.

**Comment by DaveMielke** [comment]
Why, on Haiku, are CS5 and CS6 equal to CS7? That's misleading. Shouldn't they
still have unique values, and their use return EINVAL?

**Comment by mmuman** [comment]
That's because we reimplemented the BeOS API, and they did that 20 years ago for some reason beyond me. Maybe someday we'll fix it, but for now we have to work around this.

**Pull request merged**
