### PR TITLE
brlapi: Make brlapi errors an enum

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by DaveMielke** [comment]
Rather than duplicate the numbers, wouldn't it work to do, for example: #define BRLAPI_ERROR_XXX BRLAPI_ERROR_XXX

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by sthibaul** [comment]
> Rather than duplicate the numbers, wouldn't it work to do, for example: #define BRLAPI_ERROR_XXX BRLAPI_ERROR_XXX

I first tried that of course, but then the binding awk scripts don't manage get the value, and miscompile everything.

**Comment by DaveMielke** [comment]
But I can fix the awk scripts. Also, the first added Java default is missing a blank line before it.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
I've created the brlapi-error-enum branch. So far, the #defines have been converted. Now working on the awk bit. When done, I'll squash before merging.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
A question: Would you like each of the enum values to specify the actual value, or just let them increment from 0?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by sthibaul** [comment]
> A question: Would you like each of the enum values to specify the actual value, or just let them increment from 0?

I'd better have the values readable in the file.

**Comment by DaveMielke** [comment]
Please check that you're happy with the brlapi-error-enum branch.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by sthibaul** [comment]
Yes, except there is a missing space in
```#defineBRLAPI_ERROR_READONLY_PARAMETER```

**Comment by DaveMielke** [comment]
Found it just after you did. I'll merge it now, then.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Pull request closed without merging**
