### PR TITLE
API connection settings fields should be const char. (ml)

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by DaveMielke** [comment]
[quoted lines by Mario Lang on 2020/02/19 at 13:00 -0800]

>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/brltty/brltty/pull/247
>
>-- Commit Summary --
>
>  * API connection settings fields should be const char. (ml)

I myself agree with you but, the last time this issue came up, Samuel and
Sébastien didn't. My preference is that they be convinced first. I believe the
argument was that assigning a malloc()ed string needs to be supported.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by DaveMielke** [comment]
Dave Mielke, le mer. 19 févr. 2020 18:10:35 -0500, a ecrit:
> [quoted lines by Mario Lang on 2020/02/19 at 13:00 -0800]
> >You can view, comment on, or merge this pull request online at:
> >
> >  https://github.com/brltty/brltty/pull/247
> >
> >-- Commit Summary --
> >
> >  * API connection settings fields should be const char. (ml)
> 
> I myself agree with you but, the last time this issue came up, Samuel and
> Sébastien didn't.

Oh, I didn't remember.

> I believe the argument was that assigning a malloc()ed string needs to
> be supported.

Looking back in my mails, I find this:

«
it means for instance that if somebody wants to do something like:

brlapi_connectionSettings_t *parameters(some args) {
        brlapi_connectionSettings_t *ret = malloc(sizeof(*ret));
        asprintf(&ret->auth, "%something", args...);
        return ret;
}

freeparameters(settings) {
        free(settings->auth);
        free(settings);
}

int main(void) {
        brlapi_connectionSettings_t * settings = fillparameters(args...);
        brlapi_openConnection(settings);
        freeparameters(settings);
}

He'd now have to put casts in various places to avoid warnings, making
programming more tedious than needed.  In general, one can see that libc
etc. never put consts in structures etc. even if it would make sense,
because of that problem.

Since these consts will not be very useful for optimization anyway
(while they will in other places you have changed), I think they would
bring more harm than good here.
»

Mario, does putting const here actually avoid some casts in your code,
or is it mostly about documenting the ownership?

Samuel

**Comment by DaveMielke** [comment]
Samuel Thibault <samuel.thibault@ens-lyon.org> writes:

> Mario, does putting const here actually avoid some casts in your code,
> or is it mostly about documenting the ownership?

I came across this issue while trying to write Rust bindings for BrlAPI.
Rust uses a tool called bindgen to automatically generate the low-level
code from a C header file.  It infers mutable fields
for the connection settings struct, which is at least inconvenient
since Rust strings are basically never mutable.
It is very likely that there are workarounds on the Rust side for this,
but its sort of stricter type system makes at least pretending that
something is mutable pretty hard.  I can manually change
these fields on the rust side from *mut to *const, so there are ways to
work around this.  However, I would have prefered to not have to do
this.

Also, its not quite clear to me when malloc'ed strings should be
deallocated.  Once brlapi__openConnection was successful?
Or once brlapi__closeConnection was called?
I.e., does BrlAPI take ownership of auth and host fields?
If no, how long does it hold onto those?

-- 
CYa,
  ⡍⠁⠗⠊⠕

**Comment by DaveMielke** [comment]
Hi,

Mario Lang (2020/02/20 07:54 +0100):
> I came across this issue while trying to write Rust bindings for
> BrlAPI.

Awesome! Thanks!!

> Also, its not quite clear to me when malloc'ed strings should be
> deallocated.  Once brlapi__openConnection was successful?

I'd say so, yes.

> Or once brlapi__closeConnection was called?

I think they don't need to stay allocated that long.

> I.e., does BrlAPI take ownership of auth and host fields?

In my understanding, it does not.

hth,

Sébastien.

**Comment by DaveMielke** [comment]
Sébastien Hinderer, le jeu. 20 févr. 2020 08:21:59 +0100, a ecrit:
> Mario Lang (2020/02/20 07:54 +0100):
> > Also, its not quite clear to me when malloc'ed strings should be
> > deallocated.  Once brlapi__openConnection was successful?
> 
> I'd say so, yes.
> 
> > Or once brlapi__closeConnection was called?
> 
> I think they don't need to stay allocated that long.
> 
> > I.e., does BrlAPI take ownership of auth and host fields?
> 
> In my understanding, it does not.

Yes, it does not.

I'd say the rust bindings autogeneration reason seems more useful than
the need for cast in the C case, then, and we can merge it.

Samuel

**Comment by DaveMielke** [comment]
[quoted lines by Samuel Thibault on 2020/02/20 at 09:08 +0100]

Hi:

>I'd say the rust bindings autogeneration reason seems more useful than
>the need for cast in the C case, then, and we can merge it.

Thanks. Done. I rebased it so it won't close automatically and I'd appreciate
it if this could be done for me.

Mario: Do you know a way I can manually close a PR with a command?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by shindere** [comment]
Dave Mielke (2020/02/20 01:57 -0800):
> [quoted lines by Samuel Thibault on 2020/02/20 at 09:08 +0100]
>
> Hi:
>
> >I'd say the rust bindings autogeneration reason seems more useful than
> >the need for cast in the C case, then, and we can merge it.
>
> Thanks. Done. I rebased it so it won't close automatically and I'd appreciate
> it if this could be done for me.
>
> Mario: Do you know a way I can manually close a PR with a command?

git hub pull close xxxx

**Comment by DaveMielke** [comment]
[quoted lines by Sébastien Hinderer on 2020/02/20 at 02:02 -0800]

Hi:

>git hub pull close xxxx

Doesn't work. It says that "close" isn't a repository.

   hub pull close 247
   fatal: 'close' does not appear to be a git repository
   fatal: Could not read from remote repository.

Note that I did "hub", not "git hub". When I mkae it a subcommand of git, I
get:

   git hub pull close 247
   git: 'hub' is not a git command. See 'git --help'.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by shindere** [comment]
I think on Debian, the hub package has installed a git-hub program.
Actually, git has the feature that if you run

git foo

it will actually run the git-foo program.

Regarding the hub command you have, do you use it? Is it working for
other things? The repository needs to be configured for that to work.
Where does your hub command come from?

Let's try to make this work if you so wish because it's really
convenient.

Here is the URLof the reposiitory where the Debian package comes from:

https://github.com/sociomantic-tsunami/git-hub

Sébastien.

**Comment by DaveMielke** [comment]
[quoted lines by Sébastien Hinderer on 2020/02/20 at 06:57 -0800]

Hi:

>Regarding the hub command you have, do you use it? 

Absolutely! I use it for things like creating pull requests, and it works just
fine.

>Where does your hub command come from?

From the Fedora package named hub. Now I'm about two Fedora releases behind the
latest (been too lazy to upgrade), so maybe it's because "hub pull close" is
recent?

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by shindere** [comment]
Dave Mielke (2020/02/20 08:59 -0800):
> From the Fedora package named hub. Now I'm about two Fedora releases behind the
> latest (been too lazy to upgrade), so maybe it's because "hub pull close" is
> recent?

I hardly believe it's that recent. But I seem to remember that there
were several implementations of this hub subcommand so you may want to
check that we use the same.

Are you able, for instance, to comment on a pull request with it?

e.g., does

hub pull comment xxx

work for you?

**Comment by DaveMielke** [comment]
[quoted lines by Sébastien Hinderer on 2020/02/20 at 12:28 -0800]

Hi:

>Are you able, for instance, to comment on a pull request with it?
>
>e.g., does
>
>hub pull comment xxx
>
>work for you?

No, it doesn't. hub --help says this:

These GitHub commands are provided by hub:
   api            Low-level GitHub API request interface
   browse         Open a GitHub page in the default browser
   ci-status      Show the status of GitHub checks for a commit
   compare        Open a compare page on GitHub
   create         Create this repository on GitHub and add GitHub as origin
   delete         Delete a repository on GitHub
   fork           Make a fork of a remote repository on GitHub and add as remote
   issue          List or create GitHub issues
   pr             List or checkout GitHub pull requests
   pull-request   Open a pull request on GitHub
   release        List or create GitHub releases
   sync           Fetch git objects from upstream and update branches

So, as you can see, there's simply no "hub pull". This is what I'd expect since
pull is a git command and the argument after "git pull" needs to be the name of
a remote. I'm wondering, therefore, if the version of hub that you're using
contains a non-standard enhancement or more.

-- 
I believe the Bible to be the very Word of God: http://Mielke.cc/bible/
Dave Mielke            | 2213 Fox Crescent | WebHome: http://Mielke.cc/
EMail: Dave@Mielke.cc  | Ottawa, Ontario   | Twitter: @Dave_Mielke
Phone: +1 613 726 0014 | Canada  K2A 1H7   |

**Comment by shindere** [comment]
Dave Mielke (2020/02/20 13:55 -0800):
> So, as you can see, there's simply no "hub pull". This is what I'd expect since
> pull is a git command and the argument after "git pull" needs to be the name of
> a remote. I'm wondering, therefore, if the version of hub that you're using
> contains a non-standard enhancement or more.

I told you, it introduces a "hub" sub-command thanks to git's mechanism
that I already explained. "pull" is thus a subcommand of that hub
subcommand. Definitely the program you are usign is different from mine.
I wouldn't say mine is strictly more powerful because there might be
things mine can't do, but as far as pull requests and issues are
concerned, my program can definitely do more. You can comment on pull
requests and issues, view them in the ocnsole, close them. You could
just clone the repo I sent you, install it in your home and give it a
try. Since mine is run with "git hub", it would not even conflict with
yours so you could use both.

**Pull request closed without merging**
